<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-EUTQRU8P" ignored="0" name="Rerun Cases" tests="2" failures="2" timestamp="2021-06-09T19:57:58 IST" time="0.108" errors="0">
  <testcase name="FirstTestCase" time="0.015" classname="handsOnSelenium.RerunFailedCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at handsOnSelenium.RerunFailedCases.FirstTestCase(RerunFailedCases.java:10)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- FirstTestCase -->
  <testcase name="SecondTestCase" time="0.002" classname="handsOnSelenium.RerunFailedCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at handsOnSelenium.RerunFailedCases.SecondTestCase(RerunFailedCases.java:15)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- SecondTestCase -->
</testsuite> <!-- Rerun Cases -->
